### PR TITLE
Bump brod version from ~> 3.9.2 to ~> 3.10

### PR DESCRIPTION
**Pull request by nandofarias**
Hey ppl,

Lately, I've run into some problems compiling an app with OTP 23.
The error was with a library named `crc32cer`.

MacOS 10.15
Elixir 1.10.4 (compiled with Erlang/OTP 23)
Erlang 23.0.2

Some logs:

```console
$ mix compile
==> supervisor3 (compile)
Compiled src/supervisor3.erl
==> gen_stage
Compiling 10 files (.ex)
Generated gen_stage app
===> Compiling telemetry
==> broadway
Compiling 18 files (.ex)
Generated broadway app
==> crc32cer (compile)
 DEPEND crc32cer.d
 ERLC   crc32cer.erl
 APP    crc32cer.app.src
 C      crc32c.c
 C      crc32c_nif.c
 LD     crc32cer.so
ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/nandofarias/Workspace/github/dashbitco/broadway_kafka/deps/crc32cer/priv/crc32cer.so] Error 1
ERROR: Command [compile] failed!
==> broadway_kafka
** (Mix) Could not compile dependency :crc32cer, "/Users/nandofarias/.asdf/installs/elixir/1.10.4-otp-23/.mix/rebar compile skip_deps=true deps_dir="/Users/nandofarias/Workspace/github/dashbitco/broadway_kafka/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile crc32cer", update it with "mix deps.update crc32cer" or clean it with "mix deps.clean crc32cer"
```

After running `mix deps.tree` I've found the following dependency tree:
`broadway_kafka` -> `brod ~> 3.9.2` -> `kafka_protocol 2.3.3` -> `crc32cer 0.1.3`

```console
$ mix deps.tree
broadway_kafka
├── broadway ~> 0.6.0 (Hex package)
│   ├── gen_stage ~> 1.0 (Hex package)
│   └── telemetry ~> 0.4.0 (Hex package)
├── brod ~> 3.9.2 (Hex package)
│   ├── kafka_protocol 2.3.3 (Hex package)
│   │   ├── crc32cer 0.1.3 (Hex package)
│   │   └── snappyer 1.2.4 (Hex package)
│   └── supervisor3 1.1.8 (Hex package)
└── ex_doc >= 0.19.0 (Hex package)
    ├── earmark ~> 1.4 (Hex package)
    └── makeup_elixir ~> 0.14 (Hex package)
        └── makeup ~> 1.0 (Hex package)
            └── nimble_parsec ~> 0.5.0 (Hex package)
```

And found that the issue was fixed on `crc32cer 0.1.4`, which was applied to `kafka_protocol 2.3.6` and applied to `brod 3.10.0`.

In this PR I've updated the `brod` dependency to the latest version `3.14.0`, unit and integration tests passed, but I can bump to a lower version like `3.10.0` if you find it would be more appropriate.

Brod 3.14.0 changelog:
https://github.com/klarna/brod/blob/3.14.0/changelog.md

Thank you!

### CODE REVIEW

**Comment by josevalim** [comment]
I am wondering if we should relax the dependency to be `~> 3.10`, assuming Brod is maintaining semver. WDYT @msaraiva?

**Comment by msaraiva** [comment]
I took a look at the changelog and it seems it will be ok to do so.

@nandofarias can you update the PR using `~> 3.10` instead?

**Comment by nandofarias** [comment]
Sure, done! Thank you, @msaraiva and @josevalim.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
