### PR TITLE
Support for SSL/TLS connections

### LINKED ISSUE #8: Connecting via SSL
Certain Kafka providers (I'm looking at [you Heroku](https://devcenter.heroku.com/articles/kafka-on-heroku#connecting-to-a-kafka-cluster)) require connecting over SSL. I didn't see any explicit options for this when poking around so I'm wondering if there are any plans to eventually support SSL. 

Also, thanks for working on a Kafka broadway implementation - super excited to see this come together ❤️

### PR DESCRIPTION
**Pull request by dtykocki**
This adds support for connecting to Kafka via SSL/TLS through
a client configuration. Any options specified through the
`client_config` will be passed to `brod:start_client/3`.

Example usage:

```
Broadway.start_link(__MODULE__,
  name: __MODULE__,
  producer: [
    module: {BroadwayKafka.Producer, [
      hosts: [localhost: 9092],
      group_id: "group_1",
      topics: ["test"],
      client_config: [
        ssl: [
          cacertfile: "ca.crt",
          keyfile: "client.key",
          certfile: "client.crt"
        ]
      ]
    ]},
    concurrency: 10
  ],
  processors: [
    default: [
      concurrency: 10
    ]
  ]
)
```

Resolves #8

### CODE REVIEW

**Comment by dtykocki** [comment]
While I'm now able to connect and receive assignments from a cluster that requires SSL/TLS, I do see a good number of `offset_out_of_range` errors followed by some crash reports: 

```
14:23:50.212 [error] Cannot fetch records from Kafka. Reason: :offset_out_of_range

14:23:50.213 [error] GenServer ExampleBroadwayKafka.MyBroadway.Broadway.Producer_3 terminating
** (FunctionClauseError) no function clause matching in BroadwayKafka.Producer.reverse_split_demand/3
    (broadway_kafka) lib/producer.ex:463: BroadwayKafka.Producer.reverse_split_demand({[], 0, 0}, 100, [])
    (broadway_kafka) lib/producer.ex:453: BroadwayKafka.Producer.split_demand/4
    (broadway_kafka) lib/producer.ex:204: BroadwayKafka.Producer.handle_info/2
    (broadway) lib/broadway/producer.ex:258: Broadway.Producer.handle_info/2
    (gen_stage) lib/gen_stage.ex:2086: GenStage.noreply_callback/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I'm fairly confident these changes are unrelated to the above issue, but I wanted to mention them now just in case.

**Comment by josevalim** [comment]
`reverse_split_demand` should definitely not crash. We will take a look. Thank you for the report!

**Comment by lucacorti** [comment]
Also getting this, and seems tohave no relationship with TLS/SSL.

**Comment by josevalim** [comment]
@lucacorti are you resetting partitions by any chance? Also, after you get these failures, does it self-heal? Or it is stuck forever?

**Comment by lucacorti** [comment]
@josevalim It's stuck in the crash loop @dtykocki showed above. I'm not resettings partitions. Simply connecting to Kafka a new consumer group and trying to consume for the first time from a topic.

**Comment by josevalim** [comment]
@lucacorti can you reproduce it reliably? How are you creating the topics and what is your Broadway config?

**Comment by msaraiva** [comment]
@lucacorti the last merged PR changed a few things regarding offset commit. Can you please update to the latest version on `master` and see if the problem persists?

Thanks!

**Comment by msaraiva** [comment]
@dtykocki thanks a lot for the PR ❤️

**Comment by dtykocki** [comment]
@msaraiva - I just took this PR and the latest master for a spin and I still see the `offset_out_of_range` error:

```
06:46:53.024 [error] GenServer ExampleBroadwayKafka.MyBroadway.Broadway.Producer_0 terminating
** (RuntimeError) cannot fetch records from Kafka (topic=whitelist partition=8 offset=0). Reason: :offset_out_of_range
    (broadway_kafka) lib/producer.ex:436: BroadwayKafka.Producer.fetch_messages_from_kafka/3
    (broadway_kafka) lib/producer.ex:218: BroadwayKafka.Producer.handle_info/2
    (broadway) lib/broadway/producer.ex:258: Broadway.Producer.handle_info/2
    (gen_stage) lib/gen_stage.ex:2086: GenStage.noreply_callback/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

The `topic=whitelist partition=8 offset=0` stands out to me because it is starting at offset 0. This topic in our Kafka cluster has offsets in the millions with only a two week retention period so there's nothing to consume at offset 0. In [Kaffe](https://github.com/spreedly/kaffe), we manage this through the the `offset_reset_policy` config: https://github.com/spreedly/kaffe#kaffe-groupmember---batch-message-consumer. What's not immediately clear to me right now, is how offsets are managed in this package.

**Comment by msaraiva** [comment]
@dtykocki we'll be following this issue on https://github.com/dashbitco/broadway_kafka/issues/11

**Pull request merged**
